### ISSUE TITLE
Težava pri preimenovanju imena

### ISSUE THREAD

**Issue by evadezelak** [evadezelak/APPR-2018-19#1]
Pozdravljeni, 
pojavila se mi je težava pri spreminjanju imena določene države v tabeli. Ime je namreč predolgo (vsebuje še opis) in bi želela imeti krajšega. 

```
levels(letalski_promet$Drzava)[levels(letalski_promet$Drzava) %in%
  c("Germany (until 1990 former territory of the FRG)")] <- c("Germany")
```

Zgornja koda sicer ne javi nobene napake, v tabeli pa se nič ne spremeni. Zanima me, kje bi lahko bila težava?

Hvala za odgovor

**Comment by jernejbanevec** [comment]
Zdravo!
Zgoraj napisana koda ne deluje, saj `R` pod spremenljivko `levels` ne najde ničesar. Kodo lahko spremeniš tako, da že pri uvozu podatkov nastaviš vrednost stolpca `Drzava` na class `factor`. Torej funkcijo `uvozi.letalski_promet` popravi tako:

```R
uvozi.letalski_promet <- function() {
  link <- "podatki/letalski_promet.html"
  stran <-  read_html(link)
  tabela <- stran %>% html_nodes(xpath="//table") %>% .[[1]] %>% html_table()
  names(tabela) <- c("Drzava", outer(2008:2018, 1:4, paste, sep="Q") %>% t() %>% .[-c(43, 44)])
  tabela <- tabela %>% melt(id.vars="Drzava", value.name="Stevilo_potnikov") %>%
    separate("variable", c("leto", "Cetrtletje"), sep="Q") %>%
    transmute(Drzava = parse_factor(Drzava), Cetrtletje=parse_date(paste(leto, (parse_number(Cetrtletje)-1)*3+1, 1, sep="-"),
                                            format="%Y-%m-%d"),
              Stevilo_potnikov=parse_number(Stevilo_potnikov, na=":", locale=locale(grouping_mark=","))) %>%
    filter(Drzava != "TIMEGEO")
  return(tabela)
}
```
Tako bi ti zgornja funkcija, ki si jo napisala morala delovati.

Lahko bi pa uporabila tudi funkcijo `gsub` na sledeči način:
```R
letalski_promet$Drzava <- gsub("^Germany.*$", "Germany", letalski_promet$Drzava)
```
Tu potem pod `levels` še vedno nimaš nič nastavljeno, le vrednosti stolpca se ti spremenijo.
