### ISSUE TITLE
Uvoz zemljevida

### ISSUE THREAD

**Issue by evadezelak** [evadezelak/APPR-2018-19#2]
Pozdravljeni, 
pri uvozu zemljevida se mi pojavlja težava glede `maptools` in sicer mi javi sledečo napako: 

Error in maptools::unionSpatialPolygons(cp, attr[, region]) : 
  isTRUE(gpclibPermitStatus()) is not TRUE

Paket `maptools` sem naložila na računalnik, zato me zanima, kje bi lahko bila težava?

Hvala za odgovor

**Comment by jernejbanevec** [comment]
Težko odgovorim, saj meni tvoja koda, ko jo poženem, dela. 
Na internetu sem dobil nasvet, ki ga lahko poskusiš in nato ponovno poženeš kodo za uvoz zemljevida:
```R
install.packages("gpclib", type="source")
```
Torej da instaliraš še `gpclib`. To morda kaj pomaga?

**Comment by evadezelak** [comment]
Ja, sedaj deluje. Najlepša hvala
