### ISSUE TITLE
Zemljevidi

### ISSUE THREAD

**Issue by jernejbanevec** [evadezelak/APPR-2018-19#3]
Zdravo!
Opazil sem naslednje manjše pomanjkljivosti:
- Pri nekaterih grafih (npr. pri grafu `graf.ustanovitve.spa`) na _x_ osi oznake let, ki niso celoštevilske npr. _2017.5_. Razlog za to je v tem, ker `R` podatke tipa `numeric` prebere kot zvezen vektor, ne pa kot diskreten vektor, kar si ti tukaj želiš. Tu seveda ne spremeni celega tipa vektorja kot celoto, vandar raje tip vektorja spremeni le pri pisanju grafa in tako namesto 
`graf.ustanovitve.spa <- ggplot(data = zdruzena.ustanovitve.spa, aes(x=leto,...`
to raje napiši tako:
`graf.ustanovitve.spa <- ggplot(data = zdruzena.ustanovitve.spa, aes(x=factor(leto),...`
Tako tip vektorja spremeniš le za namen risanja grafa.

- Pri nekaterih grafih imaš legendo poimenovano npr. `COUNTRY`. To svetujem da pretvoriš v slovensko ime, npr. `Država`. V ta namen lahko grafu prišteješ še:
```R
+ guides(color=guide_legend(title="Željeno ime"))
```
To spremeni ime legende grafa, ki predstavlja parameter `color`.

- Če želiš pa iz poročila odstraniti opozorilo, ki nastane z uvozom zemljevida, pod naslovom _Analiza in vizualizacija podatkov_, to lahko storiš tako, da po tem ko opozoril ne potrebuješ več narediš naslednje:
1. iz `vizualizacija.r` odstraniš uvoz kode iz vzorčnega repozitorija (ali to le zakomentiraš), saj se znotraj dela kode `libraries.r` že požene tvoja funkcija `uvozi.zemljevid.r`,
2. znotraj definicije tvoje funkcije `uvozi.zemljevid.r` spremeniš naslednji del kode
`
zemljevid <- readOGR(shp, ime.zemljevida)
`
v
`
zemljevid <- readOGR(shp, ime.zemljevida, verbose = FALSE)
`

V kolikor pa si problema #1 in #2 uspešno razrešila, ju lahko zapreš s klikom na **Close issue** oziroma **Close and comment**, če obenem še kaj napišeš.

**Comment by evadezelak** [comment]
Najlepša hvala! Sem spremenila in upam, da je sedaj uredu.
